version: "3.7"

services:
  base:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ..:/app
    user: node
    working_dir: /app
    environment:
      STORACHA_KEY: abcd
      STORACHA_PROOF: abcd
      ENVIRONMENT: test
      GANACHE_PRIMARY_MNEMONIC: someone token phrase mouse prison great priority cactus boost solid leave profit long bar door
      GANACHE_PRIMARY_HOST: ganache
      GANACHE_PORT: 8545
    
  test-runner:
    extends:
      service: base
    depends_on:
      - ganache
    command: "npm run test"

  start-dev:
    extends:
      service: base
    depends_on:
      - ganache
    command: "npm run start:dev"

  ganache:
    image: trufflesuite/ganache
    command: >-
      --wallet.mnemonic "someone token phrase mouse prison great priority cactus boost solid leave profit long bar door" 
      --wallet.defaultBalance 1000000 
      --chain.chainId 100
