Transform: AWS::Serverless-2016-10-31
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Environment:
    Type: String
  DdexSequencerAddress:
    Type: String
  AutoPublishAlias:
    Type: String

Globals:
  Function:
    Runtime: "nodejs22.x"
    Timeout: 240
    MemorySize: 512
    Environment:
      Variables:
        TEMP_PATH: /tmp
        ENVIRONMENT: !Ref Environment
        SECRETS_PATH: !Sub ${Environment}/StorachaBridge
        DDEX_SEQUENCER_ADDRESS: !Ref DdexSequencerAddress
        NO_COLOR: true

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: StorachaBridge
      StageName: !Ref Environment
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"

  NestJsApp:
    Type: AWS::Serverless::Function
    Properties:
      Tracing: Active
      CodeUri: ./storacha-bridge.zip
      Handler: out/storacha-bridge/lambdaEntrypoint.app
      MemorySize: 512
      AutoPublishAlias: !Ref AutoPublishAlias
      # ReservedConcurrentExecutions: 1
      Events:
        NestJs:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /{whatever+}
            Method: ANY
      Policies:
        - SecretsManagerReadWrite

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/"