name: Deploy

on:
  push:
    tags:
      - "*"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
            node-version: 22.14

      - name: "Setup environment"
        run: npm i -g jq.node
        shell: bash

      - name: "Bootstrap"
        run: npm i
        shell: bash

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.IAM_WORKFLOW_ROLE }}
          role-session-name: session-id-${{ github.run_id }}
          role-duration-seconds: 1200

      - name: "Source Sentry config"
        run: |
            echo "SENTRY_DSN=${{ secrets.SENTRY_DSN }}" >> $GITHUB_ENV
            echo "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> $GITHUB_ENV

      - name: "Build zip"
        run: make storacha-bridge.zip
        working-directory: infrastructure

      - name: "Deploy infrastructure to AWS"
        run: make deploy-stage
        working-directory: infrastructure
    
    #   - name: Create Sentry release
    #     uses: getsentry/action-release@v3
    #     env:
    #       SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    #       SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
    #       SENTRY_PROJECT: ${{ env.CRATE_NAME }}
    #     with:
    #       release: ${{ env.VERSION }}
    #       release_prefix: "@"
        