name: "Storacha Bridge tests"

# on: 
#   pull_request:
#     paths:
#       - 'src/**'
  
on:
    workflow_dispatch:

jobs:
  storacha-bridge-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
            node-version: 22.14

      - name: "Setup environment"
        run: npm i -g jq.node

        shell: bash

      - name: "Bootstrap"
        run: npm i
        shell: bash

      - name: "run tests"
        run: |
          docker compose build --build-arg UID=$(id -u) --build-arg GID=$(id -g)
          docker compose -f docker/test-runner.yaml run test-runner
